WIP
Signed-off-by: Benjamin Gilbert <bgilbert@cs.cmu.edu>

diff --git a/.github/workflows/windows.yml b/.github/workflows/windows.yml
--- a/.github/workflows/windows.yml
+++ b/.github/workflows/windows.yml
@@ -5,6 +5,10 @@ name: Windows
 on:
   workflow_call:
     inputs:
+      builder_repo_and_digest:
+        description: Docker repo and image digest for the builder container
+        required: true
+        type: string
       openslide_repo:
         description: Override OpenSlide with this repo
         required: false
@@ -52,7 +56,7 @@ jobs:
   sdist:
     name: Build source zip
     runs-on: ubuntu-latest
-    container: ghcr.io/openslide/winbuild-builder:latest
+    container: ${{ inputs.builder_repo_and_digest }}
     outputs:
       artifact: ${{ steps.prep.outputs.artifact }}
       version_suffix: ${{ steps.prep.outputs.version_suffix }}
@@ -119,7 +123,7 @@ jobs:
     name: Build
     needs: sdist
     runs-on: ubuntu-latest
-    container: ghcr.io/openslide/winbuild-builder:latest
+    container: ${{ inputs.builder_repo_and_digest }}
     strategy:
       matrix:
         bits: [32, 64]
@@ -149,7 +153,12 @@ jobs:
           if [ "${{ inputs.werror }}" = true ]; then
               werror="-w"
           fi
-          ./build.sh -m${{ matrix.bits }} ${suffix:+-s$suffix} \
+          digest=$(cut -f2 -d@ <<<"${{ inputs.builder_repo_and_digest }}")
+          if ! grep -q ^sha256: <<<"${digest}"; then
+              echo "Missing image digest in builder container ref"
+              exit 1
+          fi
+          ./build.sh -c "${digest}" -m${{ matrix.bits }} ${suffix:+-s$suffix} \
               -p "${{ inputs.pkgver }}" $werror bdist
           mkdir -p "artifacts/${{ needs.sdist.outputs.artifact }}"
           mv "openslide-win${{ matrix.bits }}-${{ inputs.pkgver }}.zip" \
